// <auto-generated />
using Data_1;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data_1.Migrations
{
    [DbContext(typeof(todolistContext))]
    partial class todolistContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0-preview.7.24405.3");

            modelBuilder.Entity("Data_1.todolistContext+Category", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("TsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("categoryid")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("categoryid");

                    b.ToTable("categorys");
                });

            modelBuilder.Entity("Data_1.todolistContext+todo", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("todos");
                });

            modelBuilder.Entity("Data_1.todolistContext+Category", b =>
                {
                    b.HasOne("Data_1.todolistContext+Category", "category")
                        .WithMany()
                        .HasForeignKey("categoryid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("category");
                });
#pragma warning restore 612, 618
        }
    }

    internal partial class todolistContext
    {
    }
    internal partial class todolistContext
    {
    }
}
